 INSERT INTO treatments(
	 title,
     short_description,
	 subtitle,
	 image_principal,
	 info_title,
	 info,
	 video,
	 description_title,
	 description,
	 bullets_title, 
	 bullets_json, 
	 footer_title, 
	 footer
) 
	VALUES
(
	'Implantes Dentales', 
    'Ante la falta o perdida de piezas dentales, se utiliza la protesis fijada por implantes dentales.',
	'La higiene bucal meticulosa y las visitas regulares odontológicas son esenciales para que los implantes dentales sean exitosos a largo plazo.', 
    'treatment_1',
    '¿Qué son los implantes dentales?',
    'Los implantes dentales son dispositivos destinados a sustituir dientes y a crear, ya sea en el maxilar superior o en la mandíbula, soportes estables, resistentes y eficaces sobres los cuales se adapta una prótesis con el fin de devolverle al paciente, parcial o completamente desdentado una función adecuada y una estética compatible con toda su función social.<br>Por tanto, un implante dental puede ser definido como un elemento que se coloca en el lugar de uno o más dientes ausentes con el objetivo de servir como una raíz artificial, sobre la que se colocará, bien atornillada o cementada, una corona individual o un puente.',
    'https://www.youtube.com/watch?v=RROciK7_KDQ&ab_channel=AngelFucaraccio',
    'Tratamiento de implantes dentales en DENTALPRO',
    'En Dental Pro este tratamiento es, por lo general, un proceso que se divide en dos partes. En el primer paso, nuestro odontólogo coloca quirúrgicamente el implante en el maxilar y seguidamente un tornillo de cicatrización. Se necesita esperar unos meses (aproximadamente 3 en la mandíbula y 5 en el maxilar superior) para que el implante cicatrice adecuadamente en el hueso, proceso llamado “oseointegración”, durante los cuales se harán revisiones periódicas y radiografías digitales de control. En el segundo paso, y transcurrido este tiempo, se toman las medidas para la fabricación de la corona o puente que tendrá el tamaño, la forma, el color y el ajuste que armonicen con los otros dientes del paciente. En el segundo paso, y transcurrido este tiempo, se toman las medidas para la fabricación de la corona o puente que tendrá el tamaño, la forma, el color y el ajuste que armonicen con los otros dientes del paciente. Una vez hecha, se colocará atornillándola o cementándola y quedará fija, pudiendo el paciente disfrutar de una vida totalmente normal desde el momento en el que abandone la clínica. El paciente además debe asumir el compromiso de mantener sanas estas estructuras.',
    'Razones para sustituir los dientes perdidos',
    'bullets_treatment1',
    null,
    'Los implantes dentales tienen el mayor índice de éxito y son también la opción que actúa de forma más parecida a los dientes naturales. Ayudan a mantener los niveles de hueso donde se han extraído los dientes. Tienen un índice de éxito excelente y en la mayoría de los casos, duran toda la vida. En términos de aspecto y función, pueden tratarse exactamente igual que un diente natural. En DENTAL PRO  ofrecemos las mejores técnicas de implantes dentales para que nuestros pacientes recuperen su sonrisa. Si te lo estás planteando, no dudes en llamarnos al 6546432154'
),
(
	'Ortodoncia', 
    'Ortodoncia tradicional con brackets. Ortopedía',
	'Nuestros tratamientos de ortodoncia en  DENTAL PRO  tienen la ventaja de proporcionarnos una boca sana, una sonrisa de aspecto agradable y dientes con mayores posibilidades de durar toda la vida.', 
    'treatment_2',
    '¿Qué es la ortodoncia?',
    'La ortodoncia es una especialidad de la odontología que se encarga de la corrección de los dientes y los huesos posicionados incorrectamente. Los dientes en mala posición y los que no articulan adecuadamente unos con otros son difíciles de mantener limpios, corren riesgos de pérdida precoz debido a caries y enfermedades periodontales, y ocasionan una tensión extra sobre los músculos de la masticación que puede generar dolores de cabeza, síndrome de ATM y molestias en cuello, hombros y espalda. Además, los dientes girados o mal posicionados comprometen nuestra estética.',
    'https://www.youtube.com/watch?v=seDIkhV8wak&ab_channel=OrtosonrisasBarranco',
    null,
    null,
    'Si tenes alguna de las siguientes afecciones, es probable que necesites un tratamiento ortodóncico:',
    'bullets_treatment2',
    null,
    null
),
(
	'Prótesis Dentales', 
    'La pérdida de un diente se puede solucionar',
	'Todos los sistemas de prótesis son eficaces y gracias a ellos se recupera, en gran medida, no sólo la forma, sino la fonética y la función masticatoria de la boca.', 
    'treatment_3',
    '¿Qué son las prótesis dentales?',
    'Es muy importante para nuestra salud la reposición inmediata de las piezas dentales perdidas. Con la excepción de las cuatro muelas de juicio, cualquier pérdida dentaria supone una implicación negativa en el resto. Y no únicamente afectará a nuestra boca, sino que puede llegar a implicar a los oídos, el cuello, la mandíbula, dificultar la masticación de alimentos… llegando incluso a constituir un déficit en la eficacia masticatoria, con consecuencias tanto funcionales como orgánicas. Cuando se pierde un diente, se produce una desorganización de las arcadas dentarias, con consecuencias locales como pueden ser la separación e inclinación de los dientes adyacentes, mayor formación de placa en esas zonas y, por tanto, más posibilidad de padecer caries y enfermedad periodontal; y consecuencias a distancia, las más frecuentes los trastornos de la articulación temporomandibular (ATM). En lo referente a la estética, una falta numerosa de dientes da un aspecto menos joven al conjunto de la cara, al aparecer surcos más pronunciados alrededor de la boca y nariz.',
    'https://www.youtube.com/watch?v=s9i6psD-Ax8&ab_channel=OrlandoFereira',
    null,
    null,
    'Tipos de Prótesis Dental:',
    'bullets_treatment3',
    '¿Cuándo son aconsejables?',
    'Estas prótesis son aconsejadas en casos de dientes muy destruidos, por grandes caries o traumatismos, en los que una carilla o un empaste tendrían muy escasa retención. Son adecuadas en dientes endodonciados, para dar consistencia a toda la pieza y evitar posibles fracturas en estas piezas que es muy frecuente que se debiliten con el paso del tiempo. Gracias a su alta estética, se utilizan también dichas prótesis en rehabilitaciones de una o varias piezas cuyo color o anatomía no son del agrado del paciente.'
),
(
	'Odontopediatría', 
    'Tratamiento focalizado en iniciar el cuidado desde la niñéz.',
	'El objetivo de la odontopediatría es lograr una buena salud oral desde la infancia para prevenir la aparición de enfermedades bucales en la edad adulta. La esencia de la odontopediatría es la prevención, la educación y el diagnóstico.', 
    'treatment_4',
    null,
    null,
    null,
    null,
    null,
    'Tratamientos indicados para los niños:',
    'bullets_treatment4',
    null,
    null
),
(
	'Blanqueamiento Dental', 
    'Tener una boca saludable implica tener dientes blancos',
	'¿Buscas una sonrisa con un color blanco resplandeciente? En DENTAL PRO, es posible. Eliminamos y aclaramos el tono de tus dientes para que obtengas unos resultados sorprendentes e inmediatos. ¡Vuelve a lucir una sonrisa juvenil y saludable! Tratamientos de estética dental seguros y eficaces que devuelven la sonrisa a nuestros pacientes.', 
    'treatment_5',
    null,
    null,
    'https://www.youtube.com/watch?v=1vwn0XXxdkM&ab_channel=Periopixel',
    null,
    null,
    null,
    'bullets_treatment5',
    null,
    null
),
(
	'Carillas Dentales', 
    'Una solución cosmética permanente para dientes fracturados, descoloridos o ligeramente desalineados.',
	'De manera indolora y mínimamente invasiva, sin inyecciones ni perforaciones las carillas ultra delgadas de porcelana proporcionan una sonrisa natural y luminosa mejorando la estética dental de nuestros pacientes.', 
    'treatment_6',
    null,
    null,
    'https://www.youtube.com/watch?v=3_FWYaL_AyE&ab_channel=Periopixel',
    null,
    null,
    null,
    'bullets_treatment6',
    null,
    null
),
(
	'Odontología Preventiva', 
    'El mejor tratamiento siempre es prevenir.',
	'En la salud bucodental en adultos y niños es fundamental la prevención. Detectar a tiempo cualquier anomalía servirá para que los tratamientos aplicados sean más efectivos. Es importante la visita al especialista al menos una vez al año y mantener durante toda la vida hábitos de higiene bucal.', 
    'treatment_7',
    'Tratamientos indicados',
    'Fluor, Radiografias, Medicion de bolsas, Limpieza profunda cada 6 meses y Exploración periodontal y periodontograma',
    null,
    null,
    null,
    null,
    null,
    null,
    null
),
(
	'Endodoncia', 
    'Tratamiento los procedimientos realizados sobre la pulpa dental',
	'El tratamiento endodóntico comprende todos aquellos procedimientos realizados sobre la pulpa dental o parte de la misma.', 
    'treatment_8',
    '¿Cuándo es necesario realizar una endodoncia?',
    'Es necesario realizar una endodoncia cuando la pulpa está afectada de forma irreversible por caries profundas o traumatismos. En estos casos el diente se vuelve sensible al frío, al calor, o a la masticación. El dolor puede ser intermitente o constante. Incluso el diente puede cambiar de color o puede aparecer un flemón. También podría estar aconsejada la endodoncia en dientes que requieren tallados exhaustivos para posterior colocación de coronas o puentes. Tras el tratamiento de endodoncia debe seguir las indicaciones que le requiera su especialista.',
    null,
    null,
    null,
    'Medios técnicos',
    'bullets_treatment8',
    null,
    null
),
(
	'Periodoncia', 
    'Tratamientos para todas aquellas enfermedades que se encuentran por fuera del diente.',
	'Muchas personas no se dan cuenta cuán comunes son las enfermedades periodontales (alrededor del diente) que comienzan lesionando las encías. Tres de cada cuatro adultos poseen algún tipo de esta enfermedad. En la mayoría de los casos, no produce dolor y por consiguiente, dicho problema pasa desapercibido. Sin embargo, su temprana detección y tratamiento son extremadamente importantes, debido a que la enfermedad periodontal termina con la vida del diente (movilidad, infección, extracción). Recordamos que es una enfermedad crónica, que su profesional tratará de frenar la evolución para salvarle sus piezas dentales y que éstas permanezcan el mayor tiempo posible en su boca.', 
    'treatment_9',
    '¿De que se trata?',
    'Gingivitis, piorrea, periodontitis, movilidad dental, etc. Los problemas en las encías son infecciones provocadas por una película de bacterias (“placa bacteriana”), que se adhiere a la superficie dental justo en el límite con las encías. Puede ocurrir a cualquier edad, pero por lo general es frecuente después de los 40 años de edad. En los primeros estadíos de la enfermedad, denominada gingivitis, las encías se tornan rojizas y sangran con facilidad. A medida que avanza la infección hacia el hueso que soporta a los dientes, recibe el nombre de periodontitis, y en este momento puede provocar un daño irreversible. Cuando avanza más todavía, el hueso y los tejidos que soportan al diente son destruidos provocando la pérdida dental. Si la placa no se remueve de forma adecua con el cepillado, libera toxinas que irritan, inflaman e infectan la encía. Más adelante provocan que los tejidos se separen del diente y formen un espacio profundo: “bolsas periodontales”. Estas bolsas, de hecho acumulan más bacterias dando lugar a un círculo vicioso que agrava la situación, migrando hacia la raíz del diente y dándole apariencia de dientes mucho más grandes, cuando lo que sucede es que el hueso se reabsorbe y se retrae la encía.',
    null,
    'Tratamientos',
    'Gingivectomía, Raspado y alisado radicular, Cirugía periodontal y tratamiento para retracción de encías',
    null,
    null,
    null,
    null
),
(10, 'Halitosis', 'Tratamientos para el mal aliento', null, null, null, null, null, null, null, null, null, null)
